name: Deploy Project to cPanel

on:
  push:
    branches:
      - main

jobs:
  quality-check:
    name: Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v4

      - name: ğŸ“‚ Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, hash, pdo_mysql

      - name: ğŸ”¨ Install Dependencies (Update)
        run: composer update --no-ansi --no-interaction --no-scripts --optimize-autoloader

      - name: âš™ï¸ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: ğŸ“¦ Build Frontend
        run: |
          npm install
          npm run build

      - name: ğŸ”§ Setup Laravel Environment
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: ğŸ§ª Run Tests
        run: php artisan test

      - name: ğŸ¨ Check Code Style (Strict)
        run: ./vendor/bin/pint --test

      - name: ğŸ” Static Analysis (PHPStan)
        run: composer phpstan

  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [quality-check]
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v4

      - name: ğŸ“‚ Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, hash, pdo_mysql

      - name: ğŸ”¨ Install Dependencies (Composer)
        run: composer install --no-ansi --no-dev --no-interaction --no-plugins --no-progress --no-scripts --optimize-autoloader

      - name: âš™ï¸ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: ğŸ“¦ Install NPM dependencies & Build
        run: |
          npm install
          npm run build

      - name: ğŸš€ Sync Files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/tests/**
            **/.env
            **/storage/framework/cache/**
            **/storage/framework/sessions/**
            **/storage/framework/views/**
            **/storage/logs/**
